// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUx86H9Pk8sZ9LFeWM_1maqSyg908sP8Y',
    appId: '1:1003192210122:web:3c88d98839ad0c4373da33',
    messagingSenderId: '1003192210122',
    projectId: 'services-app-70555',
    authDomain: 'services-app-70555.firebaseapp.com',
    storageBucket: 'services-app-70555.firebasestorage.app',
    measurementId: 'G-9J1GMHXPGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_aBQQc2N_Qge28tpso11rmEpTuty2FCY',
    appId: '1:1003192210122:android:134025e747ade37873da33',
    messagingSenderId: '1003192210122',
    projectId: 'services-app-70555',
    storageBucket: 'services-app-70555.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFOPmd2isSylxpGhfvJJ05UFfNcBjaFuE',
    appId: '1:1003192210122:ios:faf3ec0e96c1a5af73da33',
    messagingSenderId: '1003192210122',
    projectId: 'services-app-70555',
    storageBucket: 'services-app-70555.firebasestorage.app',
    androidClientId: '1003192210122-alja58hgshav5ja205pnuagfu3ok5gfp.apps.googleusercontent.com',
    iosClientId: '1003192210122-sqf8o7lf79djleht0sse5qctermktld8.apps.googleusercontent.com',
    iosBundleId: 'com.example.serviceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFOPmd2isSylxpGhfvJJ05UFfNcBjaFuE',
    appId: '1:1003192210122:ios:faf3ec0e96c1a5af73da33',
    messagingSenderId: '1003192210122',
    projectId: 'services-app-70555',
    storageBucket: 'services-app-70555.firebasestorage.app',
    androidClientId: '1003192210122-alja58hgshav5ja205pnuagfu3ok5gfp.apps.googleusercontent.com',
    iosClientId: '1003192210122-sqf8o7lf79djleht0sse5qctermktld8.apps.googleusercontent.com',
    iosBundleId: 'com.example.serviceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUx86H9Pk8sZ9LFeWM_1maqSyg908sP8Y',
    appId: '1:1003192210122:web:60f26956973007a373da33',
    messagingSenderId: '1003192210122',
    projectId: 'services-app-70555',
    authDomain: 'services-app-70555.firebaseapp.com',
    storageBucket: 'services-app-70555.firebasestorage.app',
    measurementId: 'G-GSFM2KBBZ2',
  );

}