// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXUbE65hOtCOEeUuq_8cWvX0Tmjh--V1s',
    appId: '1:112121777645:web:c01a700e7b5b0cd851ebe4',
    messagingSenderId: '112121777645',
    projectId: 'presto-daaed',
    authDomain: 'presto-daaed.firebaseapp.com',
    storageBucket: 'presto-daaed.firebasestorage.app',
    measurementId: 'G-302X5H568V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd74o3jz8he4UpU0C5wOBiPVKYfhqjjqE',
    appId: '1:112121777645:android:560a0019cf58b83a51ebe4',
    messagingSenderId: '112121777645',
    projectId: 'presto-daaed',
    storageBucket: 'presto-daaed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyqBoExILTymXGicsIvb6jJyyXpkkWscA',
    appId: '1:112121777645:ios:cba93f527235d78a51ebe4',
    messagingSenderId: '112121777645',
    projectId: 'presto-daaed',
    storageBucket: 'presto-daaed.firebasestorage.app',
    iosBundleId: 'com.example.serviceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFOPmd2isSylxpGhfvJJ05UFfNcBjaFuE',
    appId: '1:112121777645:ios:cba93f527235d78a51ebe4',
    messagingSenderId: '112121777645',
    projectId: 'presto-daaed',
    storageBucket: 'presto-daaed.firebasestorage.app',
    androidClientId: '1003192210122-alja58hgshav5ja205pnuagfu3ok5gfp.apps.googleusercontent.com',
    iosClientId: '1003192210122-sqf8o7lf79djleht0sse5qctermktld8.apps.googleusercontent.com',
    iosBundleId: 'com.example.serviceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUx86H9Pk8sZ9LFeWM_1maqSyg908sP8Y',
    appId: '1:112121777645:web:c01a700e7b5b0cd851ebe4',
    messagingSenderId: '112121777645',
    projectId: 'presto-daaed',
    authDomain: 'presto-daaed.firebaseapp.com',
    storageBucket: 'presto-daaed.firebasestorage.app',
    measurementId: 'G-GSFM2KBBZ2',
  );

}